kumuluzee:
  name: code-ide
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/IDEMetadataPS
      connection-url: jdbc:postgresql://localhost:5433/ide-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
